---
- name: Update CUBE configuration
  hosts: GPB_CUBE
  tasks:
  # #run show run on a device
  # - name: run show running-config on remote devices
  #   ios_command:
  #     commands: show running
  #   register: config

  # #save running-config on a local drive
  # - name: Save config to local file
  #   copy:
  #     content: "{{ config.stdout[0] }}"
  #     dest: "/etc/ansible/backup/{{ inventory_hostname }}/running-config_{{lookup('pipe','date +%Y%m%d_%H:%M:%S')}}"

  - name: backup
    ios_config:
      backup: yes

  #load variables for translations and dial-peers
  - name: Load vars
    include_vars:
      dir: vars/
      extensions: 
        - yaml
      #depth: 1

  #check if specified translations rules are already exist
  - name: Check translation rules in new config
    include: tasks/check_translation_rule.yaml
      translation_rule_number={{ item.translation_rule_number }}
    with_items: "{{ translation_rules }}" 

  #check if specified translations profiles are already exist
  - name: Check translation profiles in new config
    include: tasks/check_translation_profile.yaml
      translation_profile_number={{ item.translation_profile_number }}
    with_items: "{{ translation_profiles }}" 

  #check if specified dial-peers are already exist
  - name: Check dialpeers in new config
    include: tasks/check_dialpeer.yaml
      dialpeer_number={{ item.dialpeer_number }}
    with_items: "{{ dialpeers }}" 

  #add translation rules one by one
  - name: Configure translation rule 
    include: tasks/translation_rule.yaml
      translation_rule_number={{ item.translation_rule_number }}
      rule_number={{ item.rule_number }}
      rule_pattern={{ item.rule_pattern }}
    with_items: "{{ translation_rules }}"  

  #add translation profiles one by one  
  - name: Configure translation profile 
    include: tasks/translation_profile.yaml
      translation_profile_number={{ item.translation_profile_number }}
      translation_direction={{ item.translation_direction }}
      translation_rule_number={{ item.translation_rule_number }}
    with_items: "{{ translation_profiles }}" 

    #add dial-peers one by one
  - name: Configure dial-peer
    include: tasks/dialpeer.yaml
      dialpeer_description={{ item.dialpeer_description }}
      destination_pattern={{ item.destination_pattern }}
      uri_from={{ item.uri_from }}
      translate_leg={{ item.translate_leg }}
      translation_profile_number={{ item.translation_profile_number }}
      answer_address={{ item.answer_address }}
      cucm_address={{ item.cucm_address }}
      codec_class_number={{ item.codec_class_number }}
      dialpeer_number={{ item.dialpeer_number }}
    with_items: "{{ dialpeers }}" 