---
#register variable for for running_config check
- name: set translation rule variable for future use
  set_fact:
    translation_rule_string: "voice translation-rule {{ translation_rule_number }}"

#get running config, sort for translation_rule
- name: get running config for translation rule {{ translation_rule_number }}
  register: translation_rule
  ios_command:
    commands: show run | i voice translation-rule {{ translation_rule_number }}

#check if translation_rule exesits on device
- name: check if translation rule {{ translation_rule_number }} exists on device
  when: translation_rule_string == translation_rule.stdout[0] and translation_rule_number != False
  fail: msg="!!! WARNING translation_rule {{ translation_rule_number }} exist on {{ inventory_hostname }}, please check config !!!"
  