---
#add dial-peer
# - name: add dialpeer {{ dialpeer_number }}
#   when: dialpeer_number is defined
#   ios_config:
#     match: line
#     lines: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} description
  when: dialpeer_description is defined
  ignore_errors: true
  ios_config:
    commands: description {{ dialpeer_description }}
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} destination_pattern
  when: destination_pattern is defined
  ignore_errors: true  
  ios_config:
    commands: destination-pattern {{ destination_pattern }}
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} uri_from
  when: uri_from is defined
  ignore_errors: true
  ios_config:
    commands: incoming uri from {{ uri_from }}
    parents: dial-peer voice {{ dialpeer_number }} voip

- debug:
    msg: translation-profile {{ translate_leg }} {{ translation_profile_number }}

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} translation_profile
  when: translate_leg is defined and translation_profile_number is defined
  ignore_errors: true
  ios_config:
    commands: translation-profile {{ translate_leg }} {{ translation_profile_number }}
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} answer_address
  when: answer_address is defined
  ignore_errors: true
  ios_config:
    commands: answer-address {{ answer_address }}
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} session_protocol
  ignore_errors: true
  ios_config:
    commands: 
      - session protocol sipv2
      - dtmf-relay rtp-nte
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} codec_class
  when: codec_class_number is defined
  ignore_errors: true
  ios_config:
    commands: voice class codec {{ codec_class_number }}
    parents: dial-peer voice {{ dialpeer_number }} voip

#add dial-peer parameters
- name: configure dialpeer {{ dialpeer_number }} cucm_address
  when: cucm_address is defined
  ignore_errors: true
  ios_config:
    commands: session target ipv4:{{ cucm_address }}
    parents: dial-peer voice {{ dialpeer_number }} voip