---
- name: configure translation-profile {{ translation_profile_number }}
  when: translation_direction is defined and translation_rule_number is defined
  ios_config:
    commands: translate {{ translation_direction }} {{ translation_rule_number }}
    parents: voice translation-profile {{ translation_profile_number }}