---
# add translation profile
- name: configure translation-profile {{ translation_profile_name }}
  when: translation_direction is defined and translation_profile_name is defined and translation_direction != False and translation_profile_name != False
  ios_config:
    commands: translate {{ translation_direction }} {{ translation_profile_name }}
    parents: voice translation-profile {{ translation_profile_number }}