---
- name: Upgrade image
  hosts: TP18719
  tasks:
  - name: Check that image exists
    stat:
      path: /mnt/download/moesk_upgrade.tgz
    register: stat_result
    sudo: true

  - name: Check that configs are exist
    stat:
      path: /mnt/download/incidents.tar.gz
    when: stat_result.stat.exists == True
    register: stat_result_2
    sudo: true

  - name: Install new image
    command: chdir=/home/pi/scr /home/pi/scr/download 7 /mnt/download/moesk_upgrade.tgz
    sudo: true
    when: stat_result_2.stat.exists == True
    register: out
  - debug: var=out.stdout_lines